"""initial schema

Revision ID: 66d32fc81637
Revises: 
Create Date: 2026-07-14 12:25:11.141258
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# Load-bearing: autogenerate renders our custom column type by its fully-qualified
# name (``app.models.types.MoneyType()``) but does not emit an import for it, so the
# migration dies with NameError at ``upgrade()``. Importing the package binds the
# name ``app``.
import app.models.types  # noqa: F401

revision: str = '66d32fc81637'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('logo_file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('whatsapp_number', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('facebook_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tiktok_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('google_maps_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('currency_symbol', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_days_before', sa.JSON(), nullable=True),
    sa.Column('reminder_audience', sa.Enum('CUSTOMER', 'OWNER', 'BOTH', name='reminderaudience'), nullable=False),
    sa.Column('reminder_send_hour', sa.Integer(), nullable=False),
    sa.Column('notify_owner_on_overdue', sa.Boolean(), nullable=False),
    sa.Column('notify_owner_on_payment', sa.Boolean(), nullable=False),
    sa.Column('email_from_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('email_reply_to', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email_signature', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('brand_color', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('retention_policy', sa.Enum('DAYS_30', 'DAYS_60', 'DAYS_90', 'NEVER', name='retentionpolicy'), nullable=False),
    sa.Column('retention_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('storage_quota_mb', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_logo_file_id'), ['logo_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_slug'), ['slug'], unique=True)

    op.create_table('archive_batch',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('state', sa.Enum('ARCHIVED', 'PENDING_DELETION', 'POSTPONED', 'RESTORED', 'DELETED', name='archivestate'), nullable=False),
    sa.Column('credit_count', sa.Integer(), nullable=False),
    sa.Column('payment_count', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('storage_bytes', sa.Integer(), nullable=False),
    sa.Column('retention_policy', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('cutoff_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('warnings_sent', sa.JSON(), nullable=True),
    sa.Column('postponed_count', sa.Integer(), nullable=False),
    sa.Column('postponed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('deleted_records_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archive_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_batch_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_batch_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_batch_delete_scheduled_for'), ['delete_scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_batch_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_batch_state'), ['state'], unique=False)
        batch_op.create_index('ix_archive_state_scheduled', ['state', 'delete_scheduled_for'], unique=False)

    op.create_table('category',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_category_business_name')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)

    op.create_table('email_log',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('template_kind', sa.Enum('REMINDER', 'RECEIPT', 'PAYMENT_CONFIRMATION', 'WELCOME', 'ADMIN_NOTIFICATION', 'OVERDUE_NOTICE', 'DATA_DELETION_WARNING', name='emailtemplatekind'), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP', name='reminderchannel'), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('to_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('to_name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('body_preview', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('credit_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_credit_id'), ['credit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_template_kind'), ['template_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_to_address'), ['to_address'], unique=False)
        batch_op.create_index('ix_emaillog_business_created', ['business_id', 'created_at'], unique=False)

    op.create_table('user',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('avatar_file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'STAFF', name='role'), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_avatar_file_id'), ['avatar_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('audit_log',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'PURGE', 'LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_RESET', 'EXPORT', 'ARCHIVE', 'RESTORE', 'MAINTENANCE', 'REMINDER', name='auditaction'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('actor_label', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_business_created', ['business_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('file_asset',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kind', sa.Enum('BUSINESS_LOGO', 'CUSTOMER_PHOTO', 'PRODUCT_IMAGE', 'INVOICE', 'RECEIPT', 'CREDIT_PHOTO', 'EXPORT', 'TEMP', name='filekind'), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('thumbnail_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('original_size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('orphaned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'checksum', name='uq_file_business_checksum')
    )
    with op.batch_alter_table('file_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_asset_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_orphaned_at'), ['orphaned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_reference_count'), ['reference_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_size_bytes'), ['size_bytes'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_storage_key'), ['storage_key'], unique=True)
        batch_op.create_index('ix_file_kind_refcount', ['kind', 'reference_count'], unique=False)

    op.create_table('notification',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kind', sa.Enum('EMAIL_SENT', 'REMINDER_SENT', 'PAYMENT_RECEIVED', 'CREDIT_OVERDUE', 'DATA_DELETION_WARNING', 'EXPORT_READY', 'STORAGE_WARNING', 'SYSTEM', name='notificationkind'), nullable=False),
    sa.Column('state', sa.Enum('UNREAD', 'READ', 'ARCHIVED', name='notificationstate'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('link', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notif_business_state_created', ['business_id', 'state', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_token',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_token_user_id'), ['user_id'], unique=False)

    op.create_table('product',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('price', app.models.types.MoneyType(), nullable=False),
    sa.Column('cost_price', app.models.types.MoneyType(), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('image_file_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'sku', name='uq_product_business_sku')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=False)

    op.create_table('refresh_token',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    op.create_table('service',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('price', app.models.types.MoneyType(), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_name'), ['name'], unique=False)

    op.create_table('customer',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('photo_file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'DEFAULTED', name='customerstatus'), nullable=False),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('emergency_contact_relation', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('credit_limit', app.models.types.MoneyType(), nullable=True),
    sa.Column('total_credit', app.models.types.MoneyType(), nullable=False),
    sa.Column('total_paid', app.models.types.MoneyType(), nullable=False),
    sa.Column('outstanding_balance', app.models.types.MoneyType(), nullable=False),
    sa.Column('credit_count', sa.Integer(), nullable=False),
    sa.Column('overdue_count', sa.Integer(), nullable=False),
    sa.Column('last_credit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_file_id'], ['file_asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'code', name='uq_customer_business_code')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_credit_score'), ['credit_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_outstanding_balance'), ['outstanding_balance'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_status'), ['status'], unique=False)

    op.create_table('email_template',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kind', sa.Enum('REMINDER', 'RECEIPT', 'PAYMENT_CONFIRMATION', 'WELCOME', 'ADMIN_NOTIFICATION', 'OVERDUE_NOTICE', 'DATA_DELETION_WARNING', name='emailtemplatekind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('body_html', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('footer_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('accent_color', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('logo_file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('show_logo', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logo_file_id'], ['file_asset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'kind', name='uq_template_business_kind')
    )
    with op.batch_alter_table('email_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_template_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_template_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_template_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_template_kind'), ['kind'], unique=False)

    op.create_table('export_job',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('format', sa.Enum('CSV', 'XLSX', 'JSON', 'PDF', name='exportformat'), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RUNNING', 'READY', 'FAILED', 'EXPIRED', name='exportstate'), nullable=False),
    sa.Column('datasets', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('requested_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file_asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_job_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_job_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_job_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_job_state'), ['state'], unique=False)
        batch_op.create_index('ix_export_state_expires', ['state', 'expires_at'], unique=False)

    op.create_table('credit',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('subtotal', app.models.types.MoneyType(), nullable=False),
    sa.Column('discount_amount', app.models.types.MoneyType(), nullable=False),
    sa.Column('tax_amount', app.models.types.MoneyType(), nullable=False),
    sa.Column('grand_total', app.models.types.MoneyType(), nullable=False),
    sa.Column('amount_paid', app.models.types.MoneyType(), nullable=False),
    sa.Column('remaining_amount', app.models.types.MoneyType(), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('reminder_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='creditstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('photo_file_ids', sa.JSON(), nullable=True),
    sa.Column('invoice_file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('created_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_batch_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_file_id'], ['file_asset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number', name='uq_credit_business_number')
    )
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_archive_batch_id'), ['archive_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index('ix_credit_business_customer', ['business_id', 'customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_credit_business_status_due', ['business_id', 'status', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_issued_date'), ['issued_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_remaining_amount'), ['remaining_amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_reminder_date'), ['reminder_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_status'), ['status'], unique=False)

    op.create_table('credit_item',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('credit_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kind', sa.Enum('PRODUCT', 'SERVICE', 'CUSTOM', name='itemkind'), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('service_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', app.models.types.MoneyType(), nullable=False),
    sa.Column('discount_amount', app.models.types.MoneyType(), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', app.models.types.MoneyType(), nullable=False),
    sa.Column('line_subtotal', app.models.types.MoneyType(), nullable=False),
    sa.Column('line_total', app.models.types.MoneyType(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_item_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_item_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_item_credit_id'), ['credit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_item_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('payment',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('credit_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('amount', app.models.types.MoneyType(), nullable=False),
    sa.Column('balance_after', app.models.types.MoneyType(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'BANK_TRANSFER', 'CARD', 'MOBILE_MONEY', 'CHEQUE', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_file_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('received_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_batch_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_file_id'], ['file_asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number', name='uq_payment_business_number')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_archive_batch_id'), ['archive_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_payment_business_paid_at', ['business_id', 'paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_credit_id'), ['credit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_voided_at'), ['voided_at'], unique=False)

    op.create_table('scheduled_reminder',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('credit_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('audience', sa.Enum('CUSTOMER', 'OWNER', 'BOTH', name='reminderaudience'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP', name='reminderchannel'), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('days_before_due', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'FAILED', 'SKIPPED', 'CANCELLED', name='reminderstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_id', 'audience', 'channel', 'scheduled_for', name='uq_reminder_credit_audience_channel_date')
    )
    with op.batch_alter_table('scheduled_reminder', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_status_scheduled', ['status', 'scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reminder_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reminder_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reminder_credit_id'), ['credit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reminder_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reminder_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reminder_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reminder_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_reminder_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reminder_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reminder_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reminder_customer_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reminder_credit_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reminder_created_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reminder_business_id'))
        batch_op.drop_index('ix_reminder_status_scheduled')

    op.drop_table('scheduled_reminder')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_voided_at'))
        batch_op.drop_index(batch_op.f('ix_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_payment_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payment_number'))
        batch_op.drop_index(batch_op.f('ix_payment_method'))
        batch_op.drop_index(batch_op.f('ix_payment_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_payment_customer_id'))
        batch_op.drop_index(batch_op.f('ix_payment_credit_id'))
        batch_op.drop_index(batch_op.f('ix_payment_created_at'))
        batch_op.drop_index('ix_payment_business_paid_at')
        batch_op.drop_index(batch_op.f('ix_payment_business_id'))
        batch_op.drop_index(batch_op.f('ix_payment_archived_at'))
        batch_op.drop_index(batch_op.f('ix_payment_archive_batch_id'))

    op.drop_table('payment')
    with op.batch_alter_table('credit_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_item_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_credit_item_credit_id'))
        batch_op.drop_index(batch_op.f('ix_credit_item_created_at'))
        batch_op.drop_index(batch_op.f('ix_credit_item_business_id'))

    op.drop_table('credit_item')
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_status'))
        batch_op.drop_index(batch_op.f('ix_credit_reminder_date'))
        batch_op.drop_index(batch_op.f('ix_credit_remaining_amount'))
        batch_op.drop_index(batch_op.f('ix_credit_number'))
        batch_op.drop_index(batch_op.f('ix_credit_issued_date'))
        batch_op.drop_index(batch_op.f('ix_credit_due_date'))
        batch_op.drop_index(batch_op.f('ix_credit_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_credit_customer_id'))
        batch_op.drop_index(batch_op.f('ix_credit_created_at'))
        batch_op.drop_index('ix_credit_business_status_due')
        batch_op.drop_index(batch_op.f('ix_credit_business_id'))
        batch_op.drop_index('ix_credit_business_customer')
        batch_op.drop_index(batch_op.f('ix_credit_archived_at'))
        batch_op.drop_index(batch_op.f('ix_credit_archive_batch_id'))

    op.drop_table('credit')
    with op.batch_alter_table('export_job', schema=None) as batch_op:
        batch_op.drop_index('ix_export_state_expires')
        batch_op.drop_index(batch_op.f('ix_export_job_state'))
        batch_op.drop_index(batch_op.f('ix_export_job_expires_at'))
        batch_op.drop_index(batch_op.f('ix_export_job_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_export_job_created_at'))
        batch_op.drop_index(batch_op.f('ix_export_job_business_id'))

    op.drop_table('export_job')
    with op.batch_alter_table('email_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_template_kind'))
        batch_op.drop_index(batch_op.f('ix_email_template_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_email_template_created_at'))
        batch_op.drop_index(batch_op.f('ix_email_template_business_id'))

    op.drop_table('email_template')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_status'))
        batch_op.drop_index(batch_op.f('ix_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_customer_outstanding_balance'))
        batch_op.drop_index(batch_op.f('ix_customer_name'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_customer_credit_score'))
        batch_op.drop_index(batch_op.f('ix_customer_created_at'))
        batch_op.drop_index(batch_op.f('ix_customer_code'))
        batch_op.drop_index(batch_op.f('ix_customer_business_id'))

    op.drop_table('customer')
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_name'))
        batch_op.drop_index(batch_op.f('ix_service_is_active'))
        batch_op.drop_index(batch_op.f('ix_service_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_service_created_at'))
        batch_op.drop_index(batch_op.f('ix_service_code'))
        batch_op.drop_index(batch_op.f('ix_service_category_id'))
        batch_op.drop_index(batch_op.f('ix_service_business_id'))

    op.drop_table('service')
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_expires_at'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_created_at'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_product_created_at'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))
        batch_op.drop_index(batch_op.f('ix_product_business_id'))
        batch_op.drop_index(batch_op.f('ix_product_barcode'))

    op.drop_table('product')
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_expires_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_created_at'))

    op.drop_table('password_reset_token')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_state'))
        batch_op.drop_index(batch_op.f('ix_notification_kind'))
        batch_op.drop_index(batch_op.f('ix_notification_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_business_id'))
        batch_op.drop_index('ix_notif_business_state_created')

    op.drop_table('notification')
    with op.batch_alter_table('file_asset', schema=None) as batch_op:
        batch_op.drop_index('ix_file_kind_refcount')
        batch_op.drop_index(batch_op.f('ix_file_asset_storage_key'))
        batch_op.drop_index(batch_op.f('ix_file_asset_size_bytes'))
        batch_op.drop_index(batch_op.f('ix_file_asset_reference_count'))
        batch_op.drop_index(batch_op.f('ix_file_asset_orphaned_at'))
        batch_op.drop_index(batch_op.f('ix_file_asset_kind'))
        batch_op.drop_index(batch_op.f('ix_file_asset_expires_at'))
        batch_op.drop_index(batch_op.f('ix_file_asset_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_file_asset_created_at'))
        batch_op.drop_index(batch_op.f('ix_file_asset_checksum'))
        batch_op.drop_index(batch_op.f('ix_file_asset_business_id'))

    op.drop_table('file_asset')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_business_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_business_created')

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_business_id'))
        batch_op.drop_index(batch_op.f('ix_user_avatar_file_id'))

    op.drop_table('user')
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index('ix_emaillog_business_created')
        batch_op.drop_index(batch_op.f('ix_email_log_to_address'))
        batch_op.drop_index(batch_op.f('ix_email_log_template_kind'))
        batch_op.drop_index(batch_op.f('ix_email_log_success'))
        batch_op.drop_index(batch_op.f('ix_email_log_payment_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_email_log_customer_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_credit_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_email_log_business_id'))

    op.drop_table('email_log')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.drop_index(batch_op.f('ix_category_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_category_created_at'))
        batch_op.drop_index(batch_op.f('ix_category_business_id'))

    op.drop_table('category')
    with op.batch_alter_table('archive_batch', schema=None) as batch_op:
        batch_op.drop_index('ix_archive_state_scheduled')
        batch_op.drop_index(batch_op.f('ix_archive_batch_state'))
        batch_op.drop_index(batch_op.f('ix_archive_batch_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_archive_batch_delete_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_archive_batch_created_at'))
        batch_op.drop_index(batch_op.f('ix_archive_batch_business_id'))

    op.drop_table('archive_batch')
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_slug'))
        batch_op.drop_index(batch_op.f('ix_business_name'))
        batch_op.drop_index(batch_op.f('ix_business_logo_file_id'))
        batch_op.drop_index(batch_op.f('ix_business_is_active'))
        batch_op.drop_index(batch_op.f('ix_business_email'))
        batch_op.drop_index(batch_op.f('ix_business_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_business_created_at'))

    op.drop_table('business')
    # ### end Alembic commands ###
