"""add w3forms_access_key to business

Revision ID: be5a621e126f
Revises: 66d32fc81637
Create Date: 2026-07-14 22:22:37.204169
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# Load-bearing: autogenerate renders our custom column type by its fully-qualified
# name (``app.models.types.MoneyType()``) but does not emit an import for it, so the
# migration dies with NameError at ``upgrade()``. Importing the package binds the
# name ``app``.
import app.models.types  # noqa: F401

revision: str = 'be5a621e126f'
down_revision: str | None = '66d32fc81637'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('w3forms_access_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('w3forms_access_key')

    # ### end Alembic commands ###
