"""add super-admin approval fields to business

Adds the four-state approval lifecycle (PENDING/APPROVED/REJECTED/SUSPENDED) plus
the reason/timestamp/actor a super-admin decision carries.

IMPORTANT -- existing tenants are backfilled to APPROVED, not PENDING. Every shop
already in the database predates this feature and was, in effect, already approved;
defaulting them to PENDING would lock every current owner (and their staff) out of
their own data on the next deploy. New registrations get PENDING from the ORM
default, not from here.

Revision ID: d1a4f7c9e820
Revises: c7e91a4b2f30
Create Date: 2026-07-15 12:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# See the note in be5a621e126f: importing the package binds the ``app`` name that
# autogenerated column types reference by their fully-qualified path.
import app.models.types  # noqa: F401

revision: str = "d1a4f7c9e820"
down_revision: str | None = "c7e91a4b2f30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("business", schema=None) as batch_op:
        # server_default backfills existing rows to APPROVED in the same statement
        # that adds the (NOT NULL) column. The default is dropped immediately after,
        # so the ORM default (PENDING) is what governs every future INSERT.
        batch_op.add_column(
            sa.Column(
                "approval_status",
                sqlmodel.sql.sqltypes.AutoString(length=16),
                nullable=False,
                server_default="APPROVED",
            )
        )
        batch_op.add_column(
            sa.Column(
                "approval_reason",
                sqlmodel.sql.sqltypes.AutoString(length=1000),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "approved_by_user_id",
                sqlmodel.sql.sqltypes.AutoString(length=32),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_business_approval_status"), ["approval_status"], unique=False
        )

    # Now that existing rows are APPROVED, drop the server_default so future inserts
    # fall through to the application-level default (PENDING).
    with op.batch_alter_table("business", schema=None) as batch_op:
        batch_op.alter_column("approval_status", server_default=None)


def downgrade() -> None:
    with op.batch_alter_table("business", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_business_approval_status"))
        batch_op.drop_column("approved_by_user_id")
        batch_op.drop_column("approved_at")
        batch_op.drop_column("approval_reason")
        batch_op.drop_column("approval_status")
